### ISSUE TITLE
Release of Pretrained Models

### ISSUE THREAD

**Issue by ldkong1205** [hmhemu/RA-Depth#4]
Hi @hmhemu, thank you for open-sourcing your work!

Could you share the pretrained weights of RA-Depth for reproduction? Thanks!

**Comment by sunstarchan** [comment]
pre-trained models are located under folder `models/RA-Depth`.

**Comment by ldkong1205** [comment]
> pre-trained models are located under folder `models/RA-Depth`.

Thanks for your reply!
